### create a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "testsingup@gmail.com",
    "password": "12345"
}

### signin a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "testsingup@gmail.com",
    "password": "12345"
}

### which user is signed in?
GET http://localhost:3000/auth/whoAmI

### sign out the user
POST http://localhost:3000/auth/signOut

### get a user
GET http://localhost:3000/auth/2

### get specific email users
GET http://localhost:3000/auth/?email=tahir@gmail.com

### delete user
DELETE http://localhost:3000/auth/6

### update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "rasheed@gmail.com"
}

### set a color
GET http://localhost:3000/auth/colors/red

### get a color
GET http://localhost:3000/auth/colors